using System.Text;
using DomainDrivenDesign.DiagramGenerators.Diagrams.UseCases;
using PlantUML.TextEncoder;

namespace DomainDrivenDesign.DiagramGenerators;

public class DocumentationGenerator
{
    private readonly DocumentationProvider _documentationProvider;
    private readonly DocumentationFormatter _documentationFormatter;

    public DocumentationGenerator(
        DocumentationProvider documentationProvider,
        DocumentationFormatter documentationFormatter)
    {
        _documentationProvider = documentationProvider;
        _documentationFormatter = documentationFormatter;
    }

    public string DocumentUseCase(Type useCaseType)
    {
        // todo: make dynamic
        var diagram = new UseCaseDiagram();
        
        diagram.AddUseCase(useCaseType);
        
        var sb = new StringBuilder();
        sb.AppendLine("# " + diagram.UseCases.First().Title);
        sb.Append("<span style=\"color:gray\">");
        sb.Append("*This document was auto-generated by DomainDrivenDesign.LivingDocumentation.*");
        sb.AppendLine("</span>");
        sb.AppendLine();
        sb.AppendLine();

        string? description = GetDescription(useCaseType);
        if (description != null)
        {
            sb.AppendLine(description);
        }

        sb.AppendLine("## Use Case Diagram");
        string plantUmlDiagram = diagram.ToPlantUml();
        var encodedDiagram = PlantUmlTextEncoder.Encode(plantUmlDiagram);
        var diagramImageUrl = "https://www.plantuml.com/plantuml/svg/" + encodedDiagram;
        var link = $"<img src=\"{diagramImageUrl}\">";
        sb.AppendLine(link);
        sb.AppendLine();

        if (diagram.Actors.Count > 0)
        {
            sb.AppendLine("## Actors");
            foreach (var actor in diagram.Actors)
            {
                sb.AppendLine("### " + actor.Title);
                // todo: Store type or store documentation?
                //description = GetDescription(actor.Type);
            }
        }

        return sb.ToString();
    }

    private string? GetDescription(Type useCaseType)
    {
        string? description = null;
        
        var summaryNode = _documentationProvider.GetDocumentation(useCaseType);
        if (summaryNode != null)
        {
            description = _documentationFormatter.Format(summaryNode);
        }

        return description;
    }
}